name: searx-instances

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        make install-all
    - name: Check
      run: |
        make check
    - name: QA
      run: |
        make qa
